storage:
  - name: 'MyStorage'
  - guid: 'b4a0effe-ab60-4f3e-96a9-39df79b80957'
    alias: 'GuidStorage'
  - name: 'MyStorage'
    alias: 'AliasStorage'
  - name: 'MyFile'

jobs:
  - name: 'Storage Test'
    tasks:
      - name: 'useCmd'
        title: 'Print variable in MyStorage'
        command: 'echo ${MyStorage.var}'
      - name: 'useCmd'
        title: 'Print variable in GuidStorage'
        command: 'echo ${GuidStorage.var}'
      - name: 'useCmd'
        title: 'Print variable in AliasStorage'
        command: 'echo ${AliasStorage.var}'
      - name: 'useFile'
        title: 'Create file MyFile.txt'
        filename: 'MyFile.txt'
        content: '${MyFile}'
      - name: 'useFile'
        title: 'Create file MyFile.txt in directory'
        filename: 'MyFile.txt'
        content: '${MyFile}'
        directory: 'blah/flah/hah'

jobs:
  - name: 'Artifact Test'
    tasks:
      - name: 'useCmd'
        title: 'Create text file with content'
        command: 'echo "Hello World" >> file.txt'
      - name: 'useArtifact'
        title: 'Upload artifact file.txt'
        file: 'file.txt'
      - name: 'useArtifact'
        title: 'Upload artifact renamed_file.txt'
        file: 'file.txt'
        targetName: 'renamed_file_01.txt'
      - name: 'useArtifact'
        title: 'Upload artifact renamed_file.txt'
        file: 'file.txt'
        targetName: 'renamed_file_02.txt'
      - name: 'useArtifact'
        title: 'Upload artifact renamed_file.txt'
        file: './file.txt'
        targetName: 'renamed_file_03.txt'

jobs:
  - name: 'job1'
    tasks:
      - name: 'useCmd'
        title: 'Run echo command'
        command: 'echo "Hello World!"'
      - name: 'useCmd'
        title: 'Run npm command'
        command: 'npm --version'
      - name: 'useCmd'
        title: 'Run tree'
        command: 'tree'
      - name: 'useCmd'
        title: 'Run timeout'
        command: 'timeout 2>NUL'
      - name: 'useCmd'
        title: 'Run npm command'
        command: 'npm --version'
      - name: 'useCmd'
        title: 'Run timeout'
        command: 'timeout 2'

jobs:
  - name: 'CI for sidneydijkstra/Vueam'
    tasks:
      - name: 'useCmd'
        title: 'Run npm version check'
        command: 'npm --version'
      - name: 'useCmd'
        title: 'Install and Build'
        directory: '/project/'
        command:
             - 'npm install'
             - 'npm run build:lib'
      - name: 'useCmd'
        title: 'Test'
        directory: '/project/'
        command:
             - 'npm run coverage'  
      - name: 'useArtifact'
        title: 'Upload coverage'
        directory: '/project/coverage'
      - name: 'useArtifact'
        title: 'Upload build'
        directory: '/project/dist'
        targetDirectory: './library'
        copyContent: true
      - name: 'useArtifact'
        title: 'Upload test'
        file: '/project/coverage/index.html'
        targetName: 'myfile.html'