log_path: 'gpb-cicd.log'

jobs:
  - name: 'job1'
    tasks:
      - name: 'useCmd'
        title: 'Run echo command'
        command: 'fasfasf'
      - name: 'useCmd'
        title: 'Run npm command'
        command: 'npm --version'