jobs:
  - name: 'job1'
    tasks:
      - name: 'useCmd'
        title: 'Run echo command'
        command: 'echo "Hello World!"'
      - name: 'useCmd'
        title: 'Run npm command'
        command: 'npm --version'
      - name: 'useCmd'
        title: 'Run tree'
        command: 'tree'